# Generated by Django 4.1.7 on 2023-03-12 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='count',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('countu', models.IntegerField(default=0)),
                ('countdeo', models.IntegerField()),
                ('countfdo', models.IntegerField()),
                ('countp', models.IntegerField(default=0)),
                ('counta', models.IntegerField(default=0)),
                ('countr', models.IntegerField(default=0)),
                ('countpr', models.IntegerField(default=0)),
                ('countT', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'count',
            },
        ),
        migrations.CreateModel(
            name='dba',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'dba',
            },
        ),
        migrations.CreateModel(
            name='deo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('pasw', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'deo',
            },
        ),
        migrations.CreateModel(
            name='fdo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'fdo',
            },
        ),
        migrations.CreateModel(
            name='patient',
            fields=[
                ('ssn', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('age', models.DecimalField(decimal_places=0, max_digits=4)),
            ],
            options={
                'db_table': 'patient',
            },
        ),
        migrations.CreateModel(
            name='physician',
            fields=[
                ('employeeid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'physician',
            },
        ),
        migrations.CreateModel(
            name='procedure',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'procedure',
            },
        ),
        migrations.CreateModel(
            name='room',
            fields=[
                ('no', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'room',
            },
        ),
        migrations.CreateModel(
            name='tested_patient',
            fields=[
                ('ssn', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tested_patient',
            },
        ),
        migrations.CreateModel(
            name='treatments',
            fields=[
                ('treatment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('patient_id', models.IntegerField()),
                ('patient_name', models.CharField(max_length=100)),
                ('symptoms', models.TextField(blank=True, null=True)),
                ('treatments', models.TextField(blank=True, null=True)),
                ('test_results', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='treatment_images/')),
            ],
        ),
        migrations.CreateModel(
            name='stay',
            fields=[
                ('stayid', models.IntegerField(primary_key=True, serialize=False)),
                ('patientid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient')),
                ('roomno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.room')),
            ],
            options={
                'db_table': 'stay',
            },
        ),
        migrations.CreateModel(
            name='prescribes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('dose', models.TextField()),
                ('patientid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient')),
                ('physicianid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.physician')),
            ],
            options={
                'db_table': 'prescribes',
            },
        ),
        migrations.CreateModel(
            name='patients',
            fields=[
                ('ssn', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('age', models.DecimalField(decimal_places=0, max_digits=4)),
                ('pcp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.physician')),
            ],
            options={
                'db_table': 'patients',
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='pcp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.physician'),
        ),
        migrations.CreateModel(
            name='completed',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('starttime', models.DateTimeField()),
                ('endtime', models.DateTimeField()),
                ('patientid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient')),
                ('physicianid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.physician')),
            ],
            options={
                'db_table': 'completed',
            },
        ),
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('starttime', models.DateTimeField()),
                ('endtime', models.DateTimeField()),
                ('patientid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient')),
                ('physicianid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.physician')),
            ],
            options={
                'db_table': 'appointment',
            },
        ),
        migrations.CreateModel(
            name='admitted',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('starttime', models.DateTimeField()),
                ('endtime', models.DateTimeField()),
                ('patientid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient')),
                ('physicianid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.physician')),
            ],
            options={
                'db_table': 'admitted',
            },
        ),
    ]
